import { DemoStageConfig } from "@/types/demo";

export const DEMO_STAGES: DemoStageConfig[] = [
  {
    key: "INITIALIZATION",
    stageNumber: 1,
    totalStages: 8,
    durationSec: 8,
    title: "MISSION INITIALIZATION",
    subtitle: "SECTOR 7B — DEPTH: -740m",
    description:
      "Self-diagnostic pre-flight checks complete. LiDAR, thermal imaging, gas sensors, SLAM navigation engine, and ad-hoc mesh telemetry online.",
    bannerTone: "cyan",
    cameraMode: "RGB",
    telemetry: {
      status: "STANDBY",
      battery: 100,
      powerDrawKw: 1.8,
      estimatedRuntimeMin: 320,
      speed: 0.0,
      headingDeg: 90,
      temperature: 36.2,
      signalStrength: 100,
      latency: 12,
      packetLoss: 0.0,
      motorCurrent: 1.4,
      lidarRateHz: 120,
      lidarPointCount: 142000,
      depthMeters: -680,
      exploredAreaPct: 10,
      position: { x: 100, y: 350, z: -680, sector: "Sector 7A", tunnelId: "TUNNEL_MAIN_A" },
      gas: { ch4: 0.1, co: 4, o2: 20.9 },
    },
    revealedTunnelCoveragePct: 15,
    activeTunnels: ["TUNNEL_MAIN_A"],
    hazards: [],
    persons: [],
    structuralAnalysis: {
      assessment: "LOW",
      fractureZone: "None Detected",
      currentDisplacementMm: 0.2,
      displacementTrend: [
        { time: "T-15m", displacementMm: 0.1, thresholdMm: 5.0 },
        { time: "T-10m", displacementMm: 0.1, thresholdMm: 5.0 },
        { time: "T-5m", displacementMm: 0.2, thresholdMm: 5.0 },
        { time: "NOW", displacementMm: 0.2, thresholdMm: 5.0 },
      ],
      displacementRateMmHr: 0.05,
      rockBoltStrainPct: 18,
      aiConfidence: 98,
      safetyMarginPct: 96,
    },
    routes: [],
    alerts: [
      {
        id: "ALT-INIT-01",
        title: "ROVER 01 INITIALIZED",
        message: "All subsystems operational. Base relay linked to subsurface mesh.",
        category: "INFO",
        roverId: "ROVER 01",
        sector: "Sector 7A",
        location: "Shaft 1 Base",
        timestamp: "09:45:00",
        acknowledged: true,
        resolved: true,
        recommendedAction: "Authorize autonomous ingress into Sector 7B.",
      },
    ],
  },
  {
    key: "DEPLOYMENT",
    stageNumber: 2,
    totalStages: 8,
    durationSec: 10,
    title: "ROVER DEPLOYMENT & INGRESS",
    subtitle: "AUTONOMOUS NAVIGATION INITIATED",
    description:
      "Rover 01 exits Subsurface Base Station, advancing through main haulage Tunnel A towards Junction Alpha at 1.2 m/s.",
    bannerTone: "cyan",
    cameraMode: "RGB",
    telemetry: {
      status: "DEPLOYING",
      battery: 98.6,
      powerDrawKw: 4.2,
      estimatedRuntimeMin: 290,
      speed: 1.2,
      headingDeg: 88,
      temperature: 38.4,
      signalStrength: 96,
      latency: 24,
      packetLoss: 0.2,
      motorCurrent: 14.2,
      lidarRateHz: 120,
      lidarPointCount: 380000,
      depthMeters: -705,
      exploredAreaPct: 35,
      position: { x: 280, y: 350, z: -705, sector: "Sector 7A", tunnelId: "TUNNEL_MAIN_A" },
      gas: { ch4: 0.3, co: 6, o2: 20.8 },
    },
    revealedTunnelCoveragePct: 38,
    activeTunnels: ["TUNNEL_MAIN_A", "TUNNEL_NORTH_FORK", "TUNNEL_SOUTH_FORK"],
    hazards: [],
    persons: [],
    structuralAnalysis: {
      assessment: "LOW",
      fractureZone: "Junction Alpha",
      currentDisplacementMm: 0.8,
      displacementTrend: [
        { time: "T-15m", displacementMm: 0.2, thresholdMm: 5.0 },
        { time: "T-10m", displacementMm: 0.4, thresholdMm: 5.0 },
        { time: "T-5m", displacementMm: 0.6, thresholdMm: 5.0 },
        { time: "NOW", displacementMm: 0.8, thresholdMm: 5.0 },
      ],
      displacementRateMmHr: 0.2,
      rockBoltStrainPct: 24,
      aiConfidence: 94,
      safetyMarginPct: 91,
    },
    routes: [],
    alerts: [
      {
        id: "ALT-DEP-01",
        title: "TUNNEL INGRESS ACTIVE",
        message: "Rover progressing into Sector 7A. SLAM odometry locked.",
        category: "INFO",
        roverId: "ROVER 01",
        sector: "Sector 7A",
        location: "Tunnel A",
        timestamp: "09:45:30",
        acknowledged: true,
        resolved: false,
        recommendedAction: "Maintain mesh repeater link on Node 02.",
      },
    ],
  },
  {
    key: "MAPPING",
    stageNumber: 3,
    totalStages: 8,
    durationSec: 10,
    title: "UNDERGROUND SLAM MAPPING",
    subtitle: "3D LIDAR POINT CLOUD SYNTHESIS",
    description:
      "LiDAR 120Hz point cloud synthesizing unknown drifts. Spatial tunnel mesh expanding across Crosscut 7B, North Drift, and South Incline.",
    bannerTone: "cyan",
    cameraMode: "RGB",
    telemetry: {
      status: "MAPPING",
      battery: 95.8,
      powerDrawKw: 4.8,
      estimatedRuntimeMin: 275,
      speed: 0.9,
      headingDeg: 45,
      temperature: 40.1,
      signalStrength: 94,
      latency: 32,
      packetLoss: 0.4,
      motorCurrent: 12.8,
      lidarRateHz: 120,
      lidarPointCount: 920000,
      depthMeters: -720,
      exploredAreaPct: 75,
      position: { x: 480, y: 220, z: -720, sector: "Sector 7B", tunnelId: "TUNNEL_NORTH_FORK" },
      gas: { ch4: 0.6, co: 8, o2: 20.8 },
    },
    revealedTunnelCoveragePct: 78,
    activeTunnels: [
      "TUNNEL_MAIN_A",
      "TUNNEL_NORTH_FORK",
      "TUNNEL_SOUTH_FORK",
      "TUNNEL_CROSSCUT_7B",
      "TUNNEL_HAZARD_PATH",
    ],
    hazards: [],
    persons: [],
    structuralAnalysis: {
      assessment: "MODERATE",
      fractureZone: "Main Haulage Bravo",
      currentDisplacementMm: 2.1,
      displacementTrend: [
        { time: "T-15m", displacementMm: 0.5, thresholdMm: 5.0 },
        { time: "T-10m", displacementMm: 1.1, thresholdMm: 5.0 },
        { time: "T-5m", displacementMm: 1.6, thresholdMm: 5.0 },
        { time: "NOW", displacementMm: 2.1, thresholdMm: 5.0 },
      ],
      displacementRateMmHr: 0.8,
      rockBoltStrainPct: 44,
      aiConfidence: 93,
      safetyMarginPct: 79,
    },
    routes: [],
    alerts: [
      {
        id: "ALT-MAP-01",
        title: "SLAM POINT CLOUD: 75% COVERAGE",
        message: "Sector 7B primary haulage arteries successfully mapped and registered.",
        category: "INFO",
        roverId: "ROVER 01",
        sector: "Sector 7B",
        location: "Junction Bravo",
        timestamp: "09:46:15",
        acknowledged: true,
        resolved: false,
        recommendedAction: "Scan forward crosscut for atmospheric anomalies.",
      },
    ],
  },
  {
    key: "HAZARD_DETECTION",
    stageNumber: 4,
    totalStages: 8,
    durationSec: 11,
    title: "HAZARD DETECTED: CH4 + STRATA CRACK",
    subtitle: "ATMOSPHERIC & STRUCTURAL WARNING IN TUNNEL B-04",
    description:
      "Explosive gas surge detected! CH4 rises to 2.4% LEL (Flammability warning threshold). Computer vision flags 8mm shear fracture along roof rib.",
    bannerTone: "warning",
    cameraMode: "RGB",
    pulseAlert: true,
    telemetry: {
      status: "ACTIVE",
      battery: 92.4,
      powerDrawKw: 5.1,
      estimatedRuntimeMin: 255,
      speed: 0.4,
      headingDeg: 125,
      temperature: 43.8,
      signalStrength: 91,
      latency: 42,
      packetLoss: 0.8,
      motorCurrent: 9.6,
      lidarRateHz: 120,
      lidarPointCount: 1450000,
      depthMeters: -736,
      exploredAreaPct: 88,
      position: { x: 580, y: 290, z: -736, sector: "Sector 7B", tunnelId: "TUNNEL_HAZARD_PATH" },
      gas: { ch4: 2.4, co: 16, o2: 19.8 },
    },
    revealedTunnelCoveragePct: 90,
    activeTunnels: [
      "TUNNEL_MAIN_A",
      "TUNNEL_NORTH_FORK",
      "TUNNEL_SOUTH_FORK",
      "TUNNEL_CROSSCUT_7B",
      "TUNNEL_HAZARD_PATH",
      "TUNNEL_SAFE_EAST",
    ],
    hazards: [
      {
        id: "HAZ-01-CH4",
        type: "METHANE",
        title: "Combustible Methane Accumulation",
        severity: "CRITICAL",
        confidence: 96,
        valueDisplay: "2.4% LEL",
        location: { x: 680, y: 360, label: "Tunnel B-04 Rib", sector: "Sector 7B" },
        timestamp: "09:47:05",
        status: "ACTIVE",
        recommendedAction: "Isolate high-voltage rover actuators. Avoid ignition sources.",
      },
      {
        id: "HAZ-02-FRACTURE",
        type: "STRUCTURAL_FRACTURE",
        title: "Roof Strata Delamination",
        severity: "WARNING",
        confidence: 92,
        valueDisplay: "8.4 mm Shear Gap",
        location: { x: 680, y: 360, label: "Tunnel B-04 Ceiling", sector: "Sector 7B" },
        timestamp: "09:47:12",
        status: "ACTIVE",
        recommendedAction: "Flag Tunnel B-04 as hazardous pass. Do not route personnel.",
      },
    ],
    persons: [],
    structuralAnalysis: {
      assessment: "HIGH",
      fractureZone: "Tunnel B-04 Rib",
      currentDisplacementMm: 8.4,
      displacementTrend: [
        { time: "T-15m", displacementMm: 1.2, thresholdMm: 5.0 },
        { time: "T-10m", displacementMm: 3.4, thresholdMm: 5.0 },
        { time: "T-5m", displacementMm: 5.8, thresholdMm: 5.0 },
        { time: "NOW", displacementMm: 8.4, thresholdMm: 5.0 },
      ],
      displacementRateMmHr: 3.2,
      rockBoltStrainPct: 86,
      aiConfidence: 95,
      safetyMarginPct: 32,
    },
    routes: [],
    alerts: [
      {
        id: "ALT-HAZ-01",
        title: "CRITICAL GAS: METHANE 2.4% LEL",
        message: "CH4 levels exceed OSHA/DGMS mine threshold in Tunnel B-04.",
        category: "CRITICAL",
        roverId: "ROVER 01",
        sector: "Sector 7B",
        location: "Tunnel B-04",
        confidence: 96,
        timestamp: "09:47:05",
        acknowledged: false,
        resolved: false,
        recommendedAction: "Reroute autonomous exploration via South Bypass Drift.",
      },
      {
        id: "ALT-HAZ-02",
        title: "STRUCTURAL INSTABILITY: 8.4mm GAP",
        message: "Roof rock delamination detected via stereo camera & LiDAR disparity.",
        category: "WARNING",
        roverId: "ROVER 01",
        sector: "Sector 7B",
        location: "Tunnel B-04",
        confidence: 92,
        timestamp: "09:47:12",
        acknowledged: false,
        resolved: false,
        recommendedAction: "Prohibit rescue team entry through Tunnel B-04.",
      },
    ],
  },
  {
    key: "SURVIVOR_DETECTION",
    stageNumber: 5,
    totalStages: 8,
    durationSec: 12,
    title: "SURVIVOR DETECTED: PRSN-01",
    subtitle: "THERMAL + RGB MULTI-SPECTRAL FUSION",
    description:
      "Thermal sensor identifies human heat signature (37.2°C) inside Refuge Chamber 7B. AI YOLO-v9 classifier confirms human survivor with 95% confidence.",
    bannerTone: "critical",
    cameraMode: "THERMAL",
    pulseAlert: true,
    telemetry: {
      status: "ACTIVE",
      battery: 89.2,
      powerDrawKw: 4.6,
      estimatedRuntimeMin: 240,
      speed: 0.6,
      headingDeg: 135,
      temperature: 42.1,
      signalStrength: 88,
      latency: 48,
      packetLoss: 0.9,
      motorCurrent: 11.2,
      lidarRateHz: 120,
      lidarPointCount: 1840000,
      depthMeters: -745,
      exploredAreaPct: 95,
      position: { x: 740, y: 460, z: -745, sector: "Sector 7B", tunnelId: "TUNNEL_SAFE_EAST" },
      gas: { ch4: 0.8, co: 12, o2: 20.4 },
    },
    revealedTunnelCoveragePct: 98,
    activeTunnels: [
      "TUNNEL_MAIN_A",
      "TUNNEL_NORTH_FORK",
      "TUNNEL_SOUTH_FORK",
      "TUNNEL_CROSSCUT_7B",
      "TUNNEL_HAZARD_PATH",
      "TUNNEL_SAFE_EAST",
      "TUNNEL_HAZ_TO_REFUGE",
    ],
    hazards: [
      {
        id: "HAZ-01-CH4",
        type: "METHANE",
        title: "Combustible Methane Accumulation",
        severity: "CRITICAL",
        confidence: 96,
        valueDisplay: "2.4% LEL",
        location: { x: 680, y: 360, label: "Tunnel B-04 Rib", sector: "Sector 7B" },
        timestamp: "09:47:05",
        status: "ACTIVE",
        recommendedAction: "Keep clear of Tunnel B-04 artery.",
      },
    ],
    persons: [
      {
        id: "PRSN-01",
        callsign: "MINER-7B-01",
        confidence: 95,
        status: "TRACKED",
        vitalStatus: "ELEVATED",
        location: { x: 860, y: 480, label: "Refuge Chamber 7B", sector: "Sector 7B" },
        distanceMeters: 42,
        detectionSource: "THERMAL + RGB",
        thermalTempC: 37.2,
        timestamp: "09:47:50",
      },
    ],
    structuralAnalysis: {
      assessment: "HIGH",
      fractureZone: "Tunnel B-04 Rib",
      currentDisplacementMm: 8.7,
      displacementTrend: [
        { time: "T-15m", displacementMm: 2.0, thresholdMm: 5.0 },
        { time: "T-10m", displacementMm: 4.8, thresholdMm: 5.0 },
        { time: "T-5m", displacementMm: 7.2, thresholdMm: 5.0 },
        { time: "NOW", displacementMm: 8.7, thresholdMm: 5.0 },
      ],
      displacementRateMmHr: 3.4,
      rockBoltStrainPct: 88,
      aiConfidence: 96,
      safetyMarginPct: 28,
    },
    routes: [],
    alerts: [
      {
        id: "ALT-SURV-01",
        title: "SURVIVOR DETECTED: PRSN-01 (95% CONF)",
        message: "Human thermal signature tracked in Refuge Chamber 7B (Distance: 42m).",
        category: "CRITICAL",
        roverId: "ROVER 01",
        sector: "Sector 7B",
        location: "Refuge Chamber 7B",
        confidence: 95,
        timestamp: "09:47:50",
        acknowledged: false,
        resolved: false,
        recommendedAction: "Execute multi-hazard AI Safe Path synthesis.",
      },
    ],
  },
  {
    key: "AI_ANALYSIS",
    stageNumber: 6,
    totalStages: 8,
    durationSec: 12,
    title: "AI RISK FUSION & SAFE PATH PLANNING",
    subtitle: "SYNTHESIS OF GAS, STRATA & SURVIVOR COORDINATES",
    description:
      "AI Pathfinding Engine rejects direct Route A (Lethal CH4 & Cave-in risk) and computes optimal ROUTE B (South Incline Bypass — 100% Safe).",
    bannerTone: "cyan",
    cameraMode: "RGB",
    telemetry: {
      status: "AUTO_NAV",
      battery: 87.1,
      powerDrawKw: 3.9,
      estimatedRuntimeMin: 230,
      speed: 0.8,
      headingDeg: 180,
      temperature: 41.5,
      signalStrength: 92,
      latency: 38,
      packetLoss: 0.5,
      motorCurrent: 10.4,
      lidarRateHz: 120,
      lidarPointCount: 2100000,
      depthMeters: -745,
      exploredAreaPct: 100,
      position: { x: 800, y: 480, z: -745, sector: "Sector 7B", tunnelId: "TUNNEL_SAFE_EAST" },
      gas: { ch4: 0.4, co: 9, o2: 20.7 },
    },
    revealedTunnelCoveragePct: 100,
    activeTunnels: [
      "TUNNEL_MAIN_A",
      "TUNNEL_NORTH_FORK",
      "TUNNEL_SOUTH_FORK",
      "TUNNEL_CROSSCUT_7B",
      "TUNNEL_HAZARD_PATH",
      "TUNNEL_SAFE_EAST",
      "TUNNEL_HAZ_TO_REFUGE",
    ],
    hazards: [
      {
        id: "HAZ-01-CH4",
        type: "METHANE",
        title: "Combustible Methane Accumulation",
        severity: "CRITICAL",
        confidence: 96,
        valueDisplay: "2.4% LEL",
        location: { x: 680, y: 360, label: "Tunnel B-04 Rib", sector: "Sector 7B" },
        timestamp: "09:47:05",
        status: "ACTIVE",
        recommendedAction: "Barricaded by Route Planning logic.",
      },
    ],
    persons: [
      {
        id: "PRSN-01",
        callsign: "MINER-7B-01",
        confidence: 95,
        status: "TRACKED",
        vitalStatus: "ELEVATED",
        location: { x: 860, y: 480, label: "Refuge Chamber 7B", sector: "Sector 7B" },
        distanceMeters: 42,
        detectionSource: "THERMAL + RGB",
        thermalTempC: 37.2,
        timestamp: "09:47:50",
      },
    ],
    structuralAnalysis: {
      assessment: "HIGH",
      fractureZone: "Tunnel B-04 Rib",
      currentDisplacementMm: 8.9,
      displacementTrend: [
        { time: "T-15m", displacementMm: 2.5, thresholdMm: 5.0 },
        { time: "T-10m", displacementMm: 5.2, thresholdMm: 5.0 },
        { time: "T-5m", displacementMm: 7.8, thresholdMm: 5.0 },
        { time: "NOW", displacementMm: 8.9, thresholdMm: 5.0 },
      ],
      displacementRateMmHr: 3.5,
      rockBoltStrainPct: 89,
      aiConfidence: 97,
      safetyMarginPct: 24,
    },
    routes: [
      {
        id: "ROUTE-A",
        name: "Route A (Direct via Tunnel B-04)",
        riskLevel: "HIGH_RISK",
        pathNodes: [
          { x: 100, y: 350 },
          { x: 280, y: 350 },
          { x: 480, y: 220 },
          { x: 680, y: 360 },
          { x: 860, y: 480 },
        ],
        lengthMeters: 580,
        estimatedTransitTimeMin: 7.2,
        hazardsAvoided: [],
        recommended: false,
        notes: "LETHAL: Crosses 2.4% CH4 gas pocket and 8.9mm roof fracture.",
      },
      {
        id: "ROUTE-B",
        name: "Route B (South Incline Bypass — RECOMMENDED)",
        riskLevel: "SAFE",
        pathNodes: [
          { x: 100, y: 350 },
          { x: 280, y: 350 },
          { x: 480, y: 480 },
          { x: 660, y: 500 },
          { x: 860, y: 480 },
        ],
        lengthMeters: 620,
        estimatedTransitTimeMin: 8.1,
        hazardsAvoided: ["Methane Zone B-04", "Roof Fracture 8.9mm"],
        recommended: true,
        notes: "100% CLEAR: Verified clear atmospheric air and structural integrity 95%.",
      },
    ],
    alerts: [
      {
        id: "ALT-ROUTE-01",
        title: "SAFE RESCUE PATH CALCULATED: ROUTE B",
        message: "Optimal extraction corridor synthesized bypassing all gas & structural hazards.",
        category: "INFO",
        roverId: "ROVER 01",
        sector: "Sector 7B",
        location: "South Incline Drift",
        timestamp: "09:48:20",
        acknowledged: true,
        resolved: false,
        recommendedAction: "Transmit navigation waypoint beacons to Rescue Command.",
      },
    ],
  },
  {
    key: "RESCUE_ALERT",
    stageNumber: 7,
    totalStages: 8,
    durationSec: 14,
    title: "RESCUE ALERT — ACTION REQUIRED",
    subtitle: "DISPATCH AUTHORIZATION FOR RESCUE TEAM DELTA",
    description:
      "Survivor confirmed in stable refuge pocket. Critical rescue dossier prepared with safe navigation route. Awaiting operator dispatch command.",
    bannerTone: "critical",
    cameraMode: "THERMAL",
    pulseAlert: true,
    telemetry: {
      status: "ACTIVE",
      battery: 85.5,
      powerDrawKw: 2.8,
      estimatedRuntimeMin: 220,
      speed: 0.0,
      headingDeg: 142,
      temperature: 40.8,
      signalStrength: 94,
      latency: 35,
      packetLoss: 0.3,
      motorCurrent: 2.1,
      lidarRateHz: 120,
      lidarPointCount: 2300000,
      depthMeters: -745,
      exploredAreaPct: 100,
      position: { x: 840, y: 480, z: -745, sector: "Sector 7B", tunnelId: "TUNNEL_SAFE_EAST" },
      gas: { ch4: 0.3, co: 8, o2: 20.8 },
    },
    revealedTunnelCoveragePct: 100,
    activeTunnels: [
      "TUNNEL_MAIN_A",
      "TUNNEL_NORTH_FORK",
      "TUNNEL_SOUTH_FORK",
      "TUNNEL_CROSSCUT_7B",
      "TUNNEL_HAZARD_PATH",
      "TUNNEL_SAFE_EAST",
      "TUNNEL_HAZ_TO_REFUGE",
    ],
    hazards: [
      {
        id: "HAZ-01-CH4",
        type: "METHANE",
        title: "Combustible Methane Accumulation",
        severity: "CRITICAL",
        confidence: 96,
        valueDisplay: "2.4% LEL",
        location: { x: 680, y: 360, label: "Tunnel B-04 Rib", sector: "Sector 7B" },
        timestamp: "09:47:05",
        status: "ACTIVE",
        recommendedAction: "Keep clear of Tunnel B-04 artery.",
      },
    ],
    persons: [
      {
        id: "PRSN-01",
        callsign: "MINER-7B-01",
        confidence: 95,
        status: "TRACKED",
        vitalStatus: "NORMAL",
        location: { x: 860, y: 480, label: "Refuge Chamber 7B", sector: "Sector 7B" },
        distanceMeters: 18,
        detectionSource: "THERMAL + RGB",
        thermalTempC: 37.0,
        timestamp: "09:48:40",
      },
    ],
    structuralAnalysis: {
      assessment: "HIGH",
      fractureZone: "Tunnel B-04 Rib",
      currentDisplacementMm: 8.9,
      displacementTrend: [
        { time: "T-15m", displacementMm: 2.5, thresholdMm: 5.0 },
        { time: "T-10m", displacementMm: 5.2, thresholdMm: 5.0 },
        { time: "T-5m", displacementMm: 7.8, thresholdMm: 5.0 },
        { time: "NOW", displacementMm: 8.9, thresholdMm: 5.0 },
      ],
      displacementRateMmHr: 3.5,
      rockBoltStrainPct: 89,
      aiConfidence: 97,
      safetyMarginPct: 24,
    },
    routes: [
      {
        id: "ROUTE-B",
        name: "Route B (South Incline Bypass)",
        riskLevel: "SAFE",
        pathNodes: [
          { x: 100, y: 350 },
          { x: 280, y: 350 },
          { x: 480, y: 480 },
          { x: 660, y: 500 },
          { x: 860, y: 480 },
        ],
        lengthMeters: 620,
        estimatedTransitTimeMin: 8.1,
        hazardsAvoided: ["Methane Zone B-04", "Roof Fracture 8.9mm"],
        recommended: true,
        notes: "Selected safe ingress route for Rapid Response Brigade.",
      },
    ],
    alerts: [
      {
        id: "ALT-DISPATCH-01",
        title: "ACTION REQUIRED: AUTHORIZE RESCUE DISPATCH",
        message: "Operator confirmation needed to deploy Rapid Response Team via Route B.",
        category: "CRITICAL",
        roverId: "ROVER 01",
        sector: "Sector 7B",
        location: "Refuge Chamber 7B",
        confidence: 95,
        timestamp: "09:49:00",
        acknowledged: false,
        resolved: false,
        recommendedAction: "Click [DISPATCH RESCUE TEAM] to transmit route coordinates to Brigade.",
      },
    ],
  },
  {
    key: "MISSION_COMPLETE",
    stageNumber: 8,
    totalStages: 8,
    durationSec: 15,
    title: "MISSION OBJECTIVE COMPLETED",
    subtitle: "RESCUE OPERATION SUCCESSFUL",
    description:
      "Mine mapped (100%), 2 hazards isolated, 1 survivor located, Route B successfully locked, and Rescue Brigade deployed.",
    bannerTone: "success",
    cameraMode: "RGB",
    telemetry: {
      status: "COMPLETED",
      battery: 84.2,
      powerDrawKw: 1.9,
      estimatedRuntimeMin: 215,
      speed: 0.0,
      headingDeg: 142,
      temperature: 39.5,
      signalStrength: 96,
      latency: 28,
      packetLoss: 0.1,
      motorCurrent: 1.2,
      lidarRateHz: 120,
      lidarPointCount: 2450000,
      depthMeters: -745,
      exploredAreaPct: 100,
      position: { x: 840, y: 480, z: -745, sector: "Sector 7B", tunnelId: "TUNNEL_SAFE_EAST" },
      gas: { ch4: 0.2, co: 6, o2: 20.9 },
    },
    revealedTunnelCoveragePct: 100,
    activeTunnels: [
      "TUNNEL_MAIN_A",
      "TUNNEL_NORTH_FORK",
      "TUNNEL_SOUTH_FORK",
      "TUNNEL_CROSSCUT_7B",
      "TUNNEL_HAZARD_PATH",
      "TUNNEL_SAFE_EAST",
      "TUNNEL_HAZ_TO_REFUGE",
    ],
    hazards: [
      {
        id: "HAZ-01-CH4",
        type: "METHANE",
        title: "Combustible Methane Accumulation",
        severity: "CRITICAL",
        confidence: 96,
        valueDisplay: "2.4% LEL",
        location: { x: 680, y: 360, label: "Tunnel B-04 Rib", sector: "Sector 7B" },
        timestamp: "09:47:05",
        status: "ISOLATED",
        recommendedAction: "Ventilation fan unit activated in Tunnel B-04.",
      },
    ],
    persons: [
      {
        id: "PRSN-01",
        callsign: "MINER-7B-01",
        confidence: 95,
        status: "RESCUED",
        vitalStatus: "NORMAL",
        location: { x: 860, y: 480, label: "Refuge Chamber 7B", sector: "Sector 7B" },
        distanceMeters: 0,
        detectionSource: "THERMAL + RGB",
        thermalTempC: 36.8,
        timestamp: "09:50:10",
      },
    ],
    structuralAnalysis: {
      assessment: "HIGH",
      fractureZone: "Tunnel B-04 Rib",
      currentDisplacementMm: 8.9,
      displacementTrend: [
        { time: "T-15m", displacementMm: 2.5, thresholdMm: 5.0 },
        { time: "T-10m", displacementMm: 5.2, thresholdMm: 5.0 },
        { time: "T-5m", displacementMm: 7.8, thresholdMm: 5.0 },
        { time: "NOW", displacementMm: 8.9, thresholdMm: 5.0 },
      ],
      displacementRateMmHr: 0.1,
      rockBoltStrainPct: 89,
      aiConfidence: 98,
      safetyMarginPct: 85,
    },
    routes: [
      {
        id: "ROUTE-B",
        name: "Route B (South Incline Bypass)",
        riskLevel: "SAFE",
        pathNodes: [
          { x: 100, y: 350 },
          { x: 280, y: 350 },
          { x: 480, y: 480 },
          { x: 660, y: 500 },
          { x: 860, y: 480 },
        ],
        lengthMeters: 620,
        estimatedTransitTimeMin: 8.1,
        hazardsAvoided: ["Methane Zone B-04", "Roof Fracture 8.9mm"],
        recommended: true,
        notes: "Rescue Team rendezvous successfully initiated.",
      },
    ],
    alerts: [
      {
        id: "ALT-COMP-01",
        title: "MISSION SUCCESS: RESCUE TEAM REACHED SURVIVOR",
        message: "PRSN-01 extracted along Route B. No casualties.",
        category: "INFO",
        roverId: "ROVER 01",
        sector: "Sector 7B",
        location: "Refuge Chamber 7B",
        timestamp: "09:50:10",
        acknowledged: true,
        resolved: true,
        recommendedAction: "Rover standby in monitoring guard mode.",
      },
    ],
  },
];
