import { CommunicationNode } from "@/types/mission";
import { MineJunction, TunnelSegment } from "@/types/map";

export const MINE_JUNCTIONS: MineJunction[] = [
  {
    id: "BASE_STATION",
    name: "Subsurface Base Station (Shaft 1)",
    x: 100,
    y: 350,
    depthMeters: -680,
    type: "SHAFT_ENTRY",
    label: "BASE 01",
  },
  {
    id: "JUNC_ALPHA",
    name: "Junction Alpha (Sector 7A)",
    x: 280,
    y: 350,
    depthMeters: -705,
    type: "JUNCTION",
    label: "J-01",
  },
  {
    id: "JUNC_BRAVO",
    name: "Junction Bravo (Main Haulage)",
    x: 480,
    y: 220,
    depthMeters: -720,
    type: "JUNCTION",
    label: "J-02A",
  },
  {
    id: "JUNC_CHARLIE",
    name: "Junction Charlie (South Incline)",
    x: 480,
    y: 480,
    depthMeters: -730,
    type: "JUNCTION",
    label: "J-02B",
  },
  {
    id: "CHAMBER_7B",
    name: "Crosscut 7B Excavation",
    x: 680,
    y: 220,
    depthMeters: -738,
    type: "CHAMBER",
    label: "SEC-7B",
  },
  {
    id: "HAZARD_ZONE_B4",
    name: "Tunnel B-04 Fracture Zone",
    x: 680,
    y: 360,
    depthMeters: -742,
    type: "COLLAPSE_ZONE",
    label: "HAZ-B04",
  },
  {
    id: "REFUGE_7B",
    name: "Refuge Chamber 7B (Survivor Location)",
    x: 860,
    y: 480,
    depthMeters: -745,
    type: "REFUGE_STATION",
    label: "PRSN-LOC",
  },
  {
    id: "NORTH_DRIFT",
    name: "North Ventilation Drift",
    x: 860,
    y: 120,
    depthMeters: -710,
    type: "CHAMBER",
    label: "N-VENT",
  },
];

export const MINE_TUNNELS: TunnelSegment[] = [
  {
    id: "TUNNEL_MAIN_A",
    name: "Tunnel A (Shaft to Alpha)",
    fromJunction: "BASE_STATION",
    toJunction: "JUNC_ALPHA",
    points: [
      { x: 100, y: 350 },
      { x: 190, y: 345 },
      { x: 280, y: 350 },
    ],
    lengthMeters: 180,
    widthMeters: 4.5,
    sector: "Sector 7A",
    status: "SAFE",
    stabilityPct: 98,
  },
  {
    id: "TUNNEL_NORTH_FORK",
    name: "Tunnel B (Alpha to Bravo - Route A Entry)",
    fromJunction: "JUNC_ALPHA",
    toJunction: "JUNC_BRAVO",
    points: [
      { x: 280, y: 350 },
      { x: 360, y: 260 },
      { x: 480, y: 220 },
    ],
    lengthMeters: 240,
    widthMeters: 4.2,
    sector: "Sector 7A/7B",
    status: "SAFE",
    stabilityPct: 92,
  },
  {
    id: "TUNNEL_SOUTH_FORK",
    name: "Tunnel C (Alpha to Charlie - Route B Safe Path)",
    fromJunction: "JUNC_ALPHA",
    toJunction: "JUNC_CHARLIE",
    points: [
      { x: 280, y: 350 },
      { x: 380, y: 440 },
      { x: 480, y: 480 },
    ],
    lengthMeters: 260,
    widthMeters: 4.8,
    sector: "Sector 7C",
    status: "SAFE",
    stabilityPct: 96,
  },
  {
    id: "TUNNEL_HAZARD_PATH",
    name: "Tunnel B-04 (Bravo through Hazard to Charlie)",
    fromJunction: "JUNC_BRAVO",
    toJunction: "HAZARD_ZONE_B4",
    points: [
      { x: 480, y: 220 },
      { x: 590, y: 280 },
      { x: 680, y: 360 },
    ],
    lengthMeters: 210,
    widthMeters: 3.8,
    sector: "Sector 7B",
    status: "HAZARDOUS",
    stabilityPct: 54,
  },
  {
    id: "TUNNEL_CROSSCUT_7B",
    name: "Tunnel D (Bravo to North Chamber)",
    fromJunction: "JUNC_BRAVO",
    toJunction: "CHAMBER_7B",
    points: [
      { x: 480, y: 220 },
      { x: 580, y: 210 },
      { x: 680, y: 220 },
    ],
    lengthMeters: 200,
    widthMeters: 4.0,
    sector: "Sector 7B",
    status: "SAFE",
    stabilityPct: 88,
  },
  {
    id: "TUNNEL_SAFE_EAST",
    name: "Tunnel E (Charlie to Refuge Chamber 7B - Route B Safe)",
    fromJunction: "JUNC_CHARLIE",
    toJunction: "REFUGE_7B",
    points: [
      { x: 480, y: 480 },
      { x: 660, y: 500 },
      { x: 770, y: 490 },
      { x: 860, y: 480 },
    ],
    lengthMeters: 380,
    widthMeters: 4.6,
    sector: "Sector 7B",
    status: "SAFE",
    stabilityPct: 95,
  },
  {
    id: "TUNNEL_HAZ_TO_REFUGE",
    name: "Tunnel B-04B (Hazard Zone to Refuge - Dangerous Route A)",
    fromJunction: "HAZARD_ZONE_B4",
    toJunction: "REFUGE_7B",
    points: [
      { x: 680, y: 360 },
      { x: 780, y: 410 },
      { x: 860, y: 480 },
    ],
    lengthMeters: 220,
    widthMeters: 3.2,
    sector: "Sector 7B",
    status: "HAZARDOUS",
    stabilityPct: 42,
  },
];

export const INITIAL_MESH_NODES: CommunicationNode[] = [
  {
    id: "NODE-01",
    name: "Base Station Relay 01",
    status: "ONLINE",
    signalPct: 99,
    latencyMs: 12,
    packetLossPct: 0.1,
    batteryPct: 100,
    location: { x: 100, y: 350, label: "BASE MESH" },
  },
  {
    id: "NODE-02",
    name: "Repeater Node 02 (Alpha)",
    status: "ONLINE",
    signalPct: 94,
    latencyMs: 24,
    packetLossPct: 0.4,
    batteryPct: 91,
    location: { x: 280, y: 350, label: "NODE 02" },
  },
  {
    id: "NODE-03",
    name: "Repeater Node 03 (Charlie Safe Bypass)",
    status: "ONLINE",
    signalPct: 88,
    latencyMs: 38,
    packetLossPct: 0.8,
    batteryPct: 84,
    location: { x: 480, y: 480, label: "NODE 03" },
  },
  {
    id: "NODE-04",
    name: "Mobile Drone Relay 04 (Near Sector 7B)",
    status: "DEGRADED",
    signalPct: 62,
    latencyMs: 95,
    packetLossPct: 4.2,
    batteryPct: 68,
    location: { x: 740, y: 460, label: "NODE 04" },
  },
];
